[functions.essl-attendance]
verify_jwt = false

[functions.essl-management]
verify_jwt = false

[functions.fatsecret-proxy]
verify_jwt = false

[functions.update-access]
verify_jwt = false

[functions.sync-member-to-device]
verify_jwt = false

[functions.check-expired-members]
verify_jwt = false
